version: '3.0'

services:
  # Nginx
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 3000:3000
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  # PHP
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-php
    restart: unless-stopped
    volumes:
      - ./:/var/www/html

  # MySQL
  mysql:
    image: mysql:5.7
    container_name: ${APP_NAME}-mysql
    restart: unless-stopped
    ports:
      - 3306:${DB_PORT}
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql

  # Phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  # Redis
  redis:
    image: "redis:alpine"
    container_name: ${APP_NAME}-redis
    ports:
      - "6379:6379"

  # Mailhog
  mailhog:
    image: mailhog/mailhog
    container_name: ${APP_NAME}-mailhog
    ports:
      - 1025:1025
      - 8025:8025

  # Node
  node:
    image: node:12.18-alpine
    container_name: ${APP_NAME}-node
    environment:
      HOST: 0.0.0.0
    command: sh -c "yarn && yarn dev"
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html

# Volumes
volumes:
  mysqldata:
    driver: local
