version: '3.0'

services:
  # Nginx
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - node

  # PHP
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-php
    restart: "always"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  # MySQL
  mysql:
    image: mysql:5.7
    container_name: ${APP_NAME}-mysql
    restart: always
    ports:
      - "3306:${DB_PORT}"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql

  # Node
  node:
    image: node:12.18-alpine
    container_name: ${APP_NAME}-node
    environment:
      HOST: 0.0.0.0
    command: sh -c "yarn && yarn dev"
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/

# Volumes
volumes:
  mysqldata:
    driver: local