export const SET_LIST = 'SET_LIST'
export const SET_MODEL = 'SET_MODEL'
export const SET_LOADING = 'SET_LOADING'
export const SET_IS_PC = 'SET_IS_PC'
export const SET_IS_SIDEBAR_COLLAPSED = 'SET_IS_SIDEBAR_COLLAPSED'
